package cmd

const (
	CREATE_SESSION_ERROR_EXIT = iota + 1
	READ_SESSION_ERROR_EXIT
	WRITE_SESSION_ERROR_EXIT
	ENCODE_SESSION_ERROR_EXIT
	DECODE_SESSION_ERROR_EXIT
	OPERATION_ERROR_EXIT
	WRONG_ARGS_EXIT
	AUTH_ERROR_EXIT
	B2_LIBRARY_ERROR_EXIT
)
